import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/footer";
import Stack from "react-bootstrap/Stack";
import ScrollTrigger from "react-scroll-trigger";
import { useState } from "react";
import CountUp from "react-countup";
import Card from "react-bootstrap/Card";
import Modal from "react-bootstrap/Modal";
import CarouselComponent from "../components/carouselComponent";
import Button from "react-bootstrap/Button";
import ClientLogo from "../components/clientLogo";
import { useForm } from "react-hook-form";
import axios from "axios";

export default function About() {
  const [counterOn, setCounterOn] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
  } = useForm();
  const [selectedOption, setSelectedOption] = useState(0);

  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
    setValue("selectOption", event.target.value);
  };

  async function onSubmitForm(values) {
    let config = {
      method: "post",
      url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/contact`,
      headers: {
        "Content-Type": "application/json",
      },
      data: values,
    };

    try {
      const response = await axios(config);
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <Head>
        <title>
          Digital Transformation for your digital transformation journey
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-min.ico" />
      </Head>
      <main>
        <section id="abot-section">
          <Header />
          <section id="abot-hero">
            <div className="container abot-container">
              <div className="row">
                <div className="whiteLink">
                  <p className="breadcrumbs-kar">
                    <Link href="/">Home</Link> <span> &#x2027; </span> About Us
                  </p>
                </div>
                <div className="col-lg-6 col-md-6">
                  <h2 className="abot-heading py-3">
                    Who are <span className="badge abot-badge">We</span> ?
                  </h2>
                  <h4 className="abot-abt">
                    <span className="badge about-badge">Mission</span> -
                    Critical Digital Solutions for Complete Business
                    Transformation
                  </h4>
                </div>
                <div className="col-lg-6 col-md-6">
                  <p className="abot-hero-para">
                    <strong>Transform your business processes</strong> by
                    migrating from legacy solution to
                    <strong> modern technology </strong> and development that
                    guarentee <strong>growth, optimization, </strong>
                    and <strong>ROI for your business</strong>
                  </p>
                  <Link href="/contact-us" passHref>
                    <Image
                      src="/images/talkimg.png"
                      width={150}
                      height={150}
                      alt="Let's Talk Image"
                      className="lts-tlk"
                    />
                  </Link>
                </div>
              </div>
            </div>
          </section>
        </section>
        <section>
          <Image
            src="/images/office-people.webp"
            width={1349}
            height={617}
            alt="People in Office Image"
            className="off-ppl"
          />
        </section>
        <section id="abot-abt">
          <div className="container abot-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> WHO WE ARE </p>
              </div>
            </Stack>
            <div className="row">
              <div className="col-lg-7 col-md-7 py-4">
                <h1 className="abot-title">
                  We are Friendly and Experienced Digital Agency
                </h1>
                <p className="abot-abt-para ">
                  2020 brought about change at an exponential rate. Businesses
                  hell-bent on maintaining their{" "}
                  <strong> traditional establishments </strong> and
                  <strong> retaining brick </strong> and{" "}
                  <strong> mortar operations </strong> were swift to adopt
                  modern solutions by taking their businesses online.
                </p>
                <p className="abot-abt-para ">
                  Minitzon was founded at the right moment to meet the
                  challenges faced by businesses and{" "}
                  <strong>
                    {" "}
                    enable them to meet their digital transformation goals.{" "}
                  </strong>{" "}
                  Established in 2020 in Chennai, Minitzon and its robust team
                  of developers and consultants have provided{" "}
                  <strong> Product Engineering </strong> and{" "}
                  <strong> Digital Transformation services </strong> to Fortune
                  500 companies and{" "}
                  <strong> start-up enterprises globally. </strong>
                </p>
                <p className="abot-abt-para">
                  Our expertise spans several versatile areas including{" "}
                  <strong>
                    {" "}
                    UX design, web & mobile applications development, Cloud,
                    DevOps. 24*7*365 infrastructure management and customer
                    service.{" "}
                  </strong>{" "}
                  Our products are designed to meet high traffic challenges and
                  complex workflows covering both{" "}
                  <strong>
                    {" "}
                    front and back-end operations for the business.{" "}
                  </strong>
                </p>
              </div>
              <div className="col-lg-5 col-md-5 tbd-dsgn">
                <ScrollTrigger
                  onEnter={() => setCounterOn(true)}
                  onExit={() => setCounterOn(false)}
                >
                  <div className="card smp-card">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/about-laun.webp"
                          width={86}
                          height={87}
                          alt="Rocket Launch Icon"
                          className="me-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="abot-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={150}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>+</span>
                        </h2>
                        <h3 className="abot-car-para"> Projects Launched</h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/analysis.webp"
                          width={86}
                          height={87}
                          alt="Analysis Icon"
                          className="me-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="abot-car-heading">
                          <span>$</span>
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={200}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>M</span>
                        </h2>
                        <h3 className="abot-car-para">
                          {" "}
                          Raised by our clients
                        </h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/business-suitcase.webp"
                          width={86}
                          height={87}
                          alt="Business Suitcase Icon"
                          className="me-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="abot-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={1000}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>+</span>
                        </h2>
                        <h3 className="abot-car-para">
                          {" "}
                          Tech experts On-board
                        </h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/coin-stack.webp"
                          width={86}
                          height={87}
                          alt="Coin Stack Icon"
                          className="me-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="abot-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={100}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>%</span>
                        </h2>
                        <h3 className="abot-car-para"> Bootstraped</h3>
                      </div>
                    </div>
                  </div>
                </ScrollTrigger>
              </div>
            </div>
          </div>
        </section>
        <section id="abot-reinventing">
          <div className="container reinvent-container">
            <div className="row">
              <div className="col-lg-6 col-md-6">
                <h2 className="abot-title">
                  Reinventing Business Environments with the Power of Technology
                </h2>
                <p className="abot-abt-para ">
                  Minitzon delivers nothing but the best{" "}
                  <strong> digital solutions to our clients </strong> with a{" "}
                  <strong> customer-centric approach. </strong> We are
                  determined to elevate your business to global competitors by
                  using <strong> cutting-edge technology </strong> implemented
                  by masterminds in the digital world. Our experts address
                  complex business challenges with forwarding and scalable
                  solutions that hold steady for{" "}
                  <strong> long-term goals </strong> and{" "}
                  <strong> bring holistic change to your business. </strong>
                </p>
                <p className="abot-abt-para">
                  Minitzon delivers nothing but the best{" "}
                  <strong> digital solutions to our clients </strong> with a{" "}
                  <strong> customer-centric approach. </strong> We are
                  determined to elevate your business to global competitors by
                  using <strong> cutting-edge technology </strong> implemented
                  by masterminds in the digital world.
                </p>
              </div>
              <div className="col-lg-6 col-md-6">
                <Card className="abot-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/3triangle.webp"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Triangle icon"
                    />
                    <h3 className="qs-card-heading">Our Values</h3>
                    <p className="qsd-para">
                      At Minitzon, we focus on offering digital solutions
                      developed with cutting-edge technology, so our clients
                      always stay ahead of the curve. With mission-critical
                      solutions, we hold a comprehensive approach to the
                      requirement at hand.
                    </p>
                  </Card.Body>
                </Card>
                <Card className="abot-customize-card mt-3">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/approachicon.webp"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Circles Collide icon"
                    />
                    <h3 className="qs-card-heading">Our Values</h3>
                    <p className="qsd-para">
                      At Minitzon, we focus on offering digital solutions
                      developed with cutting-edge technology, so our clients
                      always stay ahead of the curve. With mission-critical
                      solutions, we hold a comprehensive approach to the
                      requirement at hand.
                    </p>
                  </Card.Body>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section id="abot-drives">
          <div className="container drives-container">
            <div className="row">
              <div className="col-lg-6 col-md-6">
                <h2 className="do-heading">
                  What Drives Us On To The Excellence Path
                </h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="dos-para">
                  Our expert teams rely on modern tools and technology that
                  provides a wide range of opportunities to build products and
                  solutions that are scalable.
                </p>
              </div>
            </div>
            <div className="row">
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="abot-drives-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/light-bulb.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="Light ideas icon"
                    />
                    <h3 className="do-card-heading">Future Proof Solutions</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="abot-drives1-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/ui-icon.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="UI Approach icon"
                    />
                    <h3 className="do-card-heading">Appealing UI/UX</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="abot-drives2-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/agile-operation.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="Agile Operation Icon"
                    />
                    <h3 className="do-card-heading">Agile Operation</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-4">
                <Card className="abot-drives-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/versatile.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="Light ideas icon"
                    />
                    <h3 className="do-card-heading">Versatile Tech Stark</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-4">
                <Card className="abot-drives1-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/res.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="Responsive Design icon"
                    />
                    <h3 className="do-card-heading">Responsive Design</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-4">
                <Card className="abot-drives2-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/clients.png"
                      width={142}
                      height={142}
                      className="dr-icon"
                      alt="Agile Operation Icon"
                    />
                    <h3 className="do-card-heading">Client-Centric Approach</h3>
                    <p className="do-para">
                      Our expert teams rely on modern tools and technology that
                      provides a wide range of opportunities to build products
                      and solutions that are scalable
                    </p>
                  </Card.Body>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section id="abot-needs">
          <div className="container needs-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> WHAT WE DO </p>
              </div>
            </Stack>
            <div className="row">
              <div className="col-lg-6 col-md-6 col-12">
                <h3 className="drive-heading pt-4">
                  We Pride Ourselves On Being The One Stop Shop For All Your
                  Needs
                </h3>
              </div>
              <div className="col-lg-6 col-md-6 col-12">
                <p className="abds-para pt-4">
                  We envision, design, build and support solutions that
                  transform and elevate your digital presence. Our expertise
                  extends to clients worldwide enabling them to achieve global
                  recognition and standard.
                </p>
              </div>
            </div>
            <div className="row">
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/app-development.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="App Development icon"
                    />
                    <h3 className="qs-card-heading">Mobile App Development</h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/mobile-app" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/backend.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Web Development icon"
                    />
                    <h3 className="qs-card-heading">Website Development</h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/web-development" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/cloud-computing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Cloud Computing icon"
                    />
                    <h3 className="qs-card-heading">Cloud Computing </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/cloud-consulting-services" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/devops.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="DevOps icon"
                    />
                    <h3 className="qs-card-heading">
                      DevOps Consulting Services{" "}
                    </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/devops-consulting-service" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/digital-marketing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Digital Marketing icon"
                    />
                    <h3 className="qs-card-heading"> Digital Marketing </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="#" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="qs-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/testing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Quality engineering and testing icon"
                    />
                    <h3 className="asd-card-heading">
                      {" "}
                      Quality Engineering & Testing{" "}
                    </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/quality-engineering-testing" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section id="abot-efficient">
          <div className="container efficient-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p>
                  {" "}
                  <strong>OUR DELIVERY MODELS</strong>{" "}
                </p>
              </div>
            </Stack>
            <div className="row pt-4">
              <div className="col-lg-6 col-md-6">
                <h2 className="abot-new-title">
                  You get more than just a testing service provider you get a
                  true partner and an extension of your team.
                </h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="abot-hero-para">
                  When you work with Testing Mavens, you get more than a{" "}
                  <strong> testing services provider </strong> -you get a{" "}
                  <strong> true partner </strong> and an extension of your team.
                  Our delivery models are designed to be{" "}
                  <strong> flexible, efficient </strong>, and{" "}
                  <strong>
                    {" "}
                    easily scalable to meet your changing needs.{" "}
                  </strong>
                </p>
              </div>
            </div>
            <div className="image-abot-container pt-5">
              <Image
                src="/images/delivery-card.png"
                width={1116}
                height={556}
                alt="Delivery Process Card"
                className="del-image"
              />
            </div>
          </div>
        </section>

        <section id="abot-payment">
          <div className="container payment-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p>
                  {" "}
                  <strong>PAYMENT MILESTONES</strong>{" "}
                </p>
              </div>
            </Stack>
            <div className="row pay-row">
              <div className="col-lg-7 col-md-6">
                <h3 className="pay-heading">
                  What are the payment milestones in the plan?
                </h3>
              </div>
              <div className="col-lg-5 col-md-6">
                <Button className="dgt-btn" href="#">
                  <img src="/images/Group309.png" width={40} /> Your deadlines
                  are our goals
                </Button>
              </div>
            </div>
            <div className="row pt-5">
              <div className="col-lg-7 col-md-7">
                <p className="pay-para">
                  We have designed the most{" "}
                  <strong> flexible payment methods </strong> so that you
                  <strong> feel safe </strong> and <strong> secure </strong>{" "}
                  while we ensure the value we provide during each release meets{" "}
                  <strong> your expectation. </strong> The payment is equally
                  divided into five milestones where you are requested to{" "}
                  <strong> pay 20% during each milestone. </strong> This ensures
                  that you <strong> feel confident </strong> and{" "}
                  <strong> pay as you go. </strong> Currently, we don't{" "}
                  <strong> accept revenue </strong> <strong>sharing </strong> or{" "}
                  <strong> equity-based payment </strong> since we might not
                  understand the industry insights. We ensure you get{" "}
                  <strong> great value </strong> and a{" "}
                  <strong>
                    {" "}
                    world-class product worth the amount you pay.
                  </strong>
                </p>
              </div>
              <div className="col-lg-5 col-md-5">
                <Image
                  src="/images/payment-mile.webp"
                  width={451}
                  height={246}
                  alt="Payment Milestone Video Image"
                  className="pay-image"
                />

                <Image
                  src="/images/watch-video.webp"
                  width={149}
                  height={150}
                  alt="Watch Video Icon Image"
                  className="wtch-vd"
                  onClick={handleShow}
                />
              </div>
            </div>
            <div className="payment-info-container">
              <Image
                src="/images/payment-mile.png"
                width={1116}
                height={179}
                alt="Payment Plan Infographics"
                className="pay-info"
                quality={100}
              />
            </div>
          </div>
        </section>
        <Modal
          show={show}
          onHide={handleClose}
          size="lg"
          aria-labelledby="contained-modal-title-vcenter"
          centered
        >
          <Modal.Header closeButton>
            <Modal.Title>Payment Milestones In A Project</Modal.Title>
          </Modal.Header>
          <Modal.Body>Add Video To Play</Modal.Body>
          <Modal.Footer>
            <Button variant="secondary">Close</Button>
            <Button variant="primary">Save changes</Button>
          </Modal.Footer>
        </Modal>

        <section className="abot-sec-cta">
          <div className="container">
            <Card className="abot-cta my-5">
              <Card.Body>
                <div className="row">
                  <div className="col-lg-7 col-md-7 col-12">
                    <Stack direction="horizontal">
                      <div className=" badge-abot-btn">
                        <img
                          src="/images/Rectangle-kariot.png"
                          className="me-2"
                          alt="design-dot"
                        />
                        <p> GET INTO TOUCH </p>
                      </div>
                    </Stack>
                    <h2 className="abtcta-heading py-3">
                    Reach out to us to identify business challenges and get efficient digital solutions.
                    </h2>
                    <Link href="/contact-us" passHref>
                      <button className="btn btn-primary get-btn">
                        Get Started Today{" "}
                        <img src="/images/material-symbols_arrow-right-alt.png" alt="Arrow Icon" />
                      </button>
                    </Link>
                  </div>
                  <div className="col-lg-5 col-md-5">
                    <Image
                      src="/images/abt-cta.webp"
                      width={600}
                      height={598}
                      alt="Chat with our expert "
                      className="abotcta-image"
                    />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </div>
        </section>

        <section id="recent-web-work">
          <div className="container new-ds">
            <div className="row">
              <div className="col-lg-3 col-md-3">
                <h2 className="case-heading">CASE STUDIES</h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="casecarousel-para">
                  In 6 years we have completed more than 200 individual projects
                  to develop modern websites, web and mobile applications for
                  clients from all over the world.
                </p>
              </div>
              <div className="col-lg-3 col-md-3">
                <button className="about-btn">
                  View All Cases{" "}
                  <img src="/images/material-symbols_arrow-right-alt.png" />
                </button>
              </div>
            </div>
            <CarouselComponent />
          </div>
        </section>

        <section id="client" className="client-section">
          <div className="container mt-5">
            <h2 className="client-title">
              Trusted By Customers, Partners and The Industry
            </h2>
            <p className="clients-text">
              At Minitzon, there is continuous learning that happens as we work
              on various projects. We also love to update and upgrade with the
              latest innovations in the field of technology and apps.
            </p>
            <ClientLogo />
          </div>
        </section>

        <section id="contct">
          <div className="container contct-container">
            <div className="row py-2">
              <h3 className="stages-heading">GET IN TOUCH</h3>
            </div>
            <div className="row">
              <div className="col-lg-8 col-md-8">
                <h2 className="contact-heading">
                  Hello! Let's make great work together.{" "}
                  <span> &#129304; </span>{" "}
                </h2>
                <p className="contact-text">
                  Take your startup to the next level. Our process revolves
                  around your unique business needs.
                </p>
              </div>
              <div className="col-lg-4 col-md-4">
                <Button href="/portfolio" className="cntct-btn">
                  <p>look at our</p> <h6>Case Studies</h6>{" "}
                </Button>
              </div>
            </div>

            <div className="row mt-5">
              <div className="col-lg-4 col-md-4">
                <h2 className="contct-heading">Hey! Got a startup idea?</h2>
                <p className="contct-para">
                  Let us give you our honest opinion. Book your{" "}
                  <strong style={{ color: "#1e2436" }}> FREE 30-Minute </strong>{" "}
                  consultation:
                </p>
                <div className="card contct-card">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/contact-us-mail.png"
                        width={50}
                        height={50}
                        alt="Contact us mail icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-10">
                      <p className="lets-para mb-0">Let's talk</p>
                      <Link href="/contact-us" className="lets-link">
                        Consult Our Experts
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Balaji Kailasasundaram
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person1.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Karthick Ganesan
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card contct-card mt-4">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/mailer-icon.png"
                        width={50}
                        height={50}
                        alt="Mailer icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-9">
                      <p className="lets-para mb-0">Send us an email</p>
                      <Link
                        href="mailto:contact@trimsel.com"
                        className="lets-link"
                      >
                        contact@trimsel.com
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-8 col-md-8">
                <div className="card cntoct-card">
                  <h3 className="stages-heading">Have an idea?</h3>
                  <h3 className="cntoct-heading">Let's get in touch</h3>

                  <form id="home-form" onSubmit={handleSubmit(onSubmitForm)}>
                    <p className="mt-5 form-lbl-para"> I'm intrested in :</p>
                    <div className="options">
                      <input
                        {...register("product")}
                        type="radio"
                        name="selectOption"
                        value="Product Development"
                        id="product"
                        checked={selectedOption === "Product Development"}
                        onChange={handleOptionChange}
                        className="form-control"
                        placeholder="product"
                      />
                      <label
                        htmlFor="product"
                        className="abot-radio-style mt-3"
                      >
                        Product Development
                      </label>

                      <input
                        {...register("mobile-app")}
                        type="radio"
                        name="selectOption"
                        value="Mobile App Development"
                        id="mobile-app"
                        checked={selectedOption === "Mobile App Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="mobile-app"
                        className="abot-radio-style mt-3"
                      >
                        Mobile App Development
                      </label>

                      <input
                        {...register("cloud-devops")}
                        type="radio"
                        name="selectOption"
                        value="Cloud and DevOps"
                        id="cloud-devops"
                        checked={selectedOption === "Cloud and DevOps"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="cloud-devops"
                        className="abot-radio-style mt-3"
                      >
                        Cloud & DevOps
                      </label>
                      <input
                        {...register("website-development")}
                        type="radio"
                        name="selectOption"
                        value="Website Development"
                        id="website-development"
                        checked={selectedOption === "Website Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="website-development"
                        className="mt-3 abot-radio-style"
                      >
                        Website Development
                      </label>
                      <input
                        {...register("digital-marketing")}
                        type="radio"
                        name="selectOption"
                        value="Digital Marketing"
                        id="digital-marketing"
                        checked={selectedOption === "Digital Marketing"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="digital-marketing"
                        className="mt-3 abot-radio-style"
                      >
                        Digital Marketing
                      </label>
                      <input
                        {...register("blockchain-development")}
                        type="radio"
                        name="selectOption"
                        value="Blockchain Development"
                        id="blockchain-development"
                        checked={selectedOption === "Blockchain Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="blockchain-development"
                        className="mt-3 abot-radio-style"
                      >
                        Block Chain Development
                      </label>
                      <input
                        {...register("quality-testing")}
                        type="radio"
                        name="selectOption"
                        value="Quality Engineering and Technology"
                        id="quality-testing"
                        checked={
                          selectedOption ===
                          "Quality Engineering and Technology"
                        }
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="quality-testing"
                        className="mt-3 abot-radio-style"
                      >
                        Quality Engineering & Technology
                      </label>
                      <input
                        {...register("other")}
                        type="radio"
                        name="selectOption"
                        value="Other"
                        id="other"
                        checked={selectedOption === "Other"}
                        onChange={handleOptionChange}
                      />
                      <label htmlFor="other" className="mt-3 abot-radio-style">
                        Other
                      </label>
                    </div>
                    <div className="row py-3">
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("name", {
                              required: {
                                value: true,
                                message: "Your name is required",
                              },
                            })}
                            type="text"
                            id="name"
                            name="name"
                            className="form-control abot-form"
                            placeholder="Full Name*"
                          />
                          <span className="error-design pt-3">
                            {errors?.name?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("phone", {
                              required: {
                                value: true,
                                message: "Your phone number is required",
                              },
                              minLength: {
                                value: 10,
                                message: "Enter a valid mobile number",
                              },
                              maxLength: {
                                value: 11,
                                message: "Enter a valid mobile number",
                              },
                            })}
                            type="tel"
                            name="phone"
                            id="phone"
                            className="form-control abot-form"
                            placeholder="Mobile Number*"
                          />
                          <span className="error-design pt-3">
                            {errors?.phone?.message}
                            {errors?.phone?.maxLength?.message}
                            {errors?.phone?.minLength?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("email", {
                              required: {
                                value: true,
                                message: "Email id is required",
                              },
                              pattern: {
                                value:
                                  /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
                                message: "Enter a valid email address",
                              },
                            })}
                            type="email"
                            name="email"
                            id="email"
                            className="form-control abot-form"
                            placeholder="Email*"
                          />
                          <span className="error-design pt-3">
                            {errors?.email?.message}
                            {errors?.email?.pattern?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("skype")}
                            type="text"
                            name="skype"
                            id="skype"
                            className="form-control abot-form"
                            placeholder="SkypeID"
                          />
                        </div>
                      </div>
                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("company")}
                            type="text"
                            name="company"
                            id="company"
                            className="form-control abot-form"
                            placeholder="Company"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <textarea
                            {...register("message")}
                            type="textarea"
                            name="message"
                            id="message"
                            className="form-control  abot-form"
                            placeholder="Your Message"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="text-right text-md-end">
                          <input type="submit" className="sbmt-btn" />
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </main>
    </>
  );
}
