import Head from 'next/head'
import Headers from '../components/headers'
import Link from 'next/link'
import Card from 'react-bootstrap/Card'
import Carousel from 'react-bootstrap/Carousel'
import { useForm } from 'react-hook-form'
import { useState, useEffect } from 'react'
import Footer from '../components/footer'


export default function Contact() {

    const {register, handleSubmit, formState : {errors}, reset, setValue} = useForm();
    const [selectedOption, setSelectedOption] = useState(0);

    const handleOptionChange = (event) => {
        setSelectedOption(event.target.value);
        setValue('selectOption', event.target.value);
    };

  async function onSubmitForm(values) {
    let config = {
      method : 'post',
      url    : `${process.env.NEXT_PUBLIC_BASE_URL}/api/contact`,
      headers : {
        'Content-Type' : 'application/json',
      },
      data : values,
    };

    try {
      const response = await axios(config);
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

    return (
        <>
        <Head>
            <title>Contact Us</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta charSet='UTF-8'/>
            <link rel="icon" href="/favicon-min.ico" />
        </Head>
        <main>
        <section className='hero-cntct'>
        <Headers />
            <div className='overlay'></div>
            
            <section className='hero'>
            <div className='container pt-3'>
              <div id='apps'>
                <div className='titles'>
                    <div className='whiteLink'>
                        <p className='breadcrumbs'>
                            <Link href = "#"> Home </Link> <span> &#x2027; </span> Contact Us 
                        </p>
                    </div>
                    <div className='cafes-inner col-lg-9 cntct-cafe'>Have a project? We would love to help.</div>
                    <p className='cntct-mozart'>
                        Tell us about your project right here or email us at <Link href="mailto:contact@trimsel.com"> contact@trimsel.com </Link> 
                    </p>
                  
                </div>
              </div>
            </div>
          </section>
        </section>
        <section id='contact' className='py-4 my-4'>
            <div className='container'>
                <div className='cntct-container'>
                    <h3 className='form-heading'><img src='/images/Group235.png' /> Let's level up your brand, together  </h3>
                    <p className='form-para'>We guarantee to get back to you within a business day</p>
            
                <div className='row'>
                    <div className='col-lg-8 col-md-8'>
                        <form id='home-form' onSubmit={handleSubmit(onSubmitForm)}>
                        <p className='mt-5 form-lbl-para'> I'm intrested in :</p>
                        <div className='options'>
                        <input 
                        {...register('product')}
                        type = "radio"
                        name = "selectOption"
                        value= "Product Development"
                        id   = "product"
                        checked={selectedOption === 'Product Development'}
                        onChange={handleOptionChange}
                        className='form-control'
                        placeholder='product'
                        />
                        <label htmlFor='product' className='radio-style mt-3' >Product Development</label>

                        <input 
                        {...register('mobile-app')}
                        type = "radio"
                        name = "selectOption"
                        value= "Mobile App Development"
                        id   = "mobile-app"
                        checked={selectedOption === 'Mobile App Development'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='mobile-app' className='radio-style mt-3' >Mobile App Development</label>

                        <input 
                        {...register('cloud-devops')}
                        type = "radio"
                        name = "selectOption"
                        value= "Cloud and DevOps"
                        id   = "cloud-devops"
                        checked={selectedOption === 'Cloud and DevOps'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='cloud-devops' className='radio-style mt-3' >Cloud & DevOps</label>
                        <input 
                        {...register('website-development')}
                        type = "radio"
                        name = "selectOption"
                        value= "Website Development"
                        id   = "website-development"
                        checked={selectedOption === 'Website Development'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='website-development' className='mt-3 radio-style' >Website Development</label>
                        <input 
                        {...register('digital-marketing')}
                        type = "radio"
                        name = "selectOption"
                        value= "Digital Marketing"
                        id   = "digital-marketing"
                        checked={selectedOption === 'Digital Marketing'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='digital-marketing' className='mt-3 radio-style' >Digital Marketing</label>
                        <input 
                        {...register('blockchain-development')}
                        type = "radio"
                        name = "selectOption"
                        value= "Blockchain Development"
                        id   = "blockchain-development"
                        checked={selectedOption === 'Blockchain Development'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='blockchain-development' className='mt-3 radio-style' >Block Chain Development</label>
                        <input 
                        {...register('quality-testing')}
                        type = "radio"
                        name = "selectOption"
                        value= "Quality Engineering and Technology"
                        id   = "quality-testing"
                        checked={selectedOption === 'Quality Engineering and Technology'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='quality-testing' className='mt-3 radio-style' >Quality Engineering & Technology</label>
                        <input 
                        {...register('other')}
                        type = "radio"
                        name = "selectOption"
                        value= "Other"
                        id   = "other"
                        checked={selectedOption === 'Other'}
                        onChange={handleOptionChange}
                        />
                        <label htmlFor='other' className='mt-3 radio-style' >Other</label>   
                    </div>
                    <div className='row py-3'>
                    <div className='col-lg-6 py-3'>
                      <div className='md-form ps-3'>
                        <label htmlFor='name' className='labels'>
                          <h5>Full Name *</h5>
                        </label>
                        <input 
                        {...register('name', {required : {
                          value : true,
                          message : "Your name is required",
                        },
                      })}
                      type = 'text'
                      id ='name'
                      name ='name'
                      className='form-control'
                      placeholder='Enter your Full Name'
                      />
                      <span className='error-design pt-3'>
                        {errors?.name?.message}
                      </span>
                      </div>
                    </div>
                    <div className='col-lg-6 py-3'>
                      <div className='md-form ps-3'>
                        <label htmlFor='phone' className='labels'>
                          <h5>Mobile Number *</h5>
                        </label>
                        <input 
                        {...register('phone', {required : {
                          value : true,
                          message : "Your phone number is required"
                        },
                        minLength : {
                          value : 10,
                          message : "Enter a valid mobile number",
                        },
                        maxLength : {
                          value : 11,
                          message : "Enter a valid mobile number"
                        },
                      })}
                      type = 'tel'
                      name = 'phone'
                      id   = 'phone'
                      className='form-control'
                      placeholder='12345 67890'
                      />
                      <span className='error-design pt-3'>
                        {errors?.phone?.message}
                        {errors?.phone?.maxLength?.message}
                        {errors?.phone?.minLength?.message}
                      </span>
                      </div>
                    </div>
                      <div className='col-lg-6 py-3'>
                        <div className='md-form ps-3'>
                          <label htmlFor='email' className='labels'>
                            <h5>Email *</h5>
                          </label>
                          <input 
                          {...register('email', {required : {
                            value : true,
                            message : "Email id is required",
                          },
                          pattern : {
                            value : /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
                            message : "Enter a valid email address"
                          },
                        })}
                        type = "email"
                        name = 'email'
                        id   = 'email'
                        className='form-control'
                        placeholder='jackdempsey@gmail.com'
                        />
                        <span className='error-design pt-3'>
                          {errors?.email?.message}
                          {errors?.email?.pattern?.message}
                        </span>
                        </div>
                      </div>
                      <div className='col-lg-6 py-3'>
                        <div className='md-form ps-3'>
                          <label htmlFor='skype' className='labels'>
                            <h5>Skype ID</h5>
                          </label>
                          <input 
                          {...register('skype')}
                          type = 'text'
                          name = 'skype'
                          id   = 'skype'
                          className= 'form-control'
                          placeholder='Enter your skype id'
                          />
                        </div>
                      </div>
                      <div className='col-lg-12 py-3'>
                        <div className='md-form ps-3'>

                          <label htmlFor='company' className='labels'>
                            <h5>Company</h5>
                          </label>
                          <input 
                          {...register('company')}
                          type = 'text'
                          name = 'company'
                          id   = 'company'
                          className='form-control'
                          placeholder = 'Tech, Marketing, Agency'
                          />
                        </div>
                      </div>
                      
                      <div className='col-lg-12 py-3'>
                        <div className='md-form ps-3'>

                          <label htmlFor = 'message' className='labels'>
                            <h5>Your Message</h5>
                          </label>
                          <textarea
                          {...register('message')}
                          type = 'textarea'
                          name = 'message'
                          id   = 'message'
                          className='form-control lg-textarea'
                          placeholder='Describe your Project'
                          />

                        </div>
                      </div>

                      <div className='col-lg-12 py-3'>
                        <div className='text-right text-md-end'>
                          <input type='submit' className='sbmt-btn' />
                        </div>
                      </div>
                  </div>
                </form>
            </div>
            <div className='col-lg-4 col-md-4'>
                <img src='/images/Letstalk.png' className='cntct-form-bg' />
            </div>
        </div>
        </div>
    </div>
</section>
<section id='office-dtls'>
    <div className='container'>
        <h2 className='office-heading'>Our Offices</h2>
        <div className='row office-row'>
            <div className='col-lg-5 col-md-5 office-column'>
                <div className='card office-card'>
                    <div className='row'>
                        <div className='col-lg-4 col-md-6 col-6'>
                            <img src='/images/iconoffice.png' />
                        </div>
                        <div className='col-lg-8 col-md-6 col-6'>
                            <h3 className='office-heading'>INDIA</h3>
                            <h4 className='office-addr'><img src = '/images/marker-icon.png' />Guindy , Chennai</h4>
                        </div>
                    </div>
                </div>
                <h3 className='office-name pt-3'>
                    <img src='/images/Rectangle116.png' /> Minitzon Technologies Private Limited
                </h3>
                <p className='office-para'>
                    21B 5th Cross St, South PhaseThiru VI KA Industrial Estate,Guindy, Chennai, Tamilnadu 600032
                </p>
                <h2 className='offices-heading pt-3'>Call Us Now !</h2>
                <Link href="tel:+917200841581">(+91)-720-084-1581</Link>
            </div>
            <div className='col-lg-7 col-md-7'>
                <img src='/images/Group2529.png' className='office-map' />
            </div>
        </div>
        
        
    </div>
</section>
<section id='testimonials' className='my-4 py-4'>
        <div className='container testimonial-container'>
          <Carousel>
            <Carousel.Item>
            <div className="card test-card">
                <h2 className="test-heading align-middle mb-0">WHAT CLIENTS SAY</h2>
                <div className="row justify-content-center align-items-center card-row"> 
                    <div className="col-lg-9">
                      <blockquote className="test-text align-middle">It's a big team and what's really good is that it's a specialized team, so that means they have to be the best at what they do. I am very happy and impressed.
                      </blockquote>
                    </div>
                    <div className="col-lg-3 text-center">
                      <img src="/images/client-feed.png" width="140" height="140"/>
                        <h4 className="test-name text-center">Kalyan <br/> Krishnamurthy</h4>
                          <p className="test-comp text-center">C.E.O  of Flipkart</p>
                    </div>
                  </div>
            </div>
            </Carousel.Item>
            <Carousel.Item>
            <div className="card test-card">
                <h2 className="test-heading align-middle mb-0">WHAT CLIENTS SAY</h2>
                <div className="row justify-content-center align-items-center card-row"> 
                    <div className="col-lg-9">
                      <blockquote className="test-text align-middle">It's a big team and what's really good is that it's a specialized team, so that means they have to be the best at what they do. I am very happy and impressed.
                      </blockquote>
                    </div>
                    <div className="col-lg-3 text-center">
                      <img src="/images/client-feed.png" width="140" height="140"/>
                        <h4 className="test-name text-center">Kalyan <br/> Krishnamurthy</h4>
                          <p className="test-comp text-center">C.E.O  of Flipkart</p>
                    </div>
                  </div>
            </div>
            </Carousel.Item>
            <Carousel.Item>
            <div className="card test-card">
                <h2 className="test-heading align-middle mb-0">WHAT CLIENTS SAY</h2>
                <div className="row justify-content-center align-items-center card-row"> 
                    <div className="col-lg-9">
                      <blockquote className="test-text align-middle">It's a big team and what's really good is that it's a specialized team, so that means they have to be the best at what they do. I am very happy and impressed.
                      </blockquote>
                    </div>
                    <div className="col-lg-3 text-center">
                      <img src="/images/client-feed.png" width="140" height="140"/>
                        <h4 className="test-name text-center">Kalyan <br/> Krishnamurthy</h4>
                          <p className="test-comp text-center">C.E.O  of Flipkart</p>
                    </div>
                  </div>
            </div>
            </Carousel.Item>
          </Carousel>
        </div>
      </section>

      <section id='contact-details'>
        <div className='container details-container'>
            <div className='details-bg'></div>
            <div className='row details-row'>
                <div className='col-lg-4 col-md-6'>
                    <h3 className='details-title'>
                        Got a Startup Idea?
                    </h3>
                    <p className='details-para pt-3'>
                    Let us give you our honest opinion. Book your <strong> FREE 30-Minute </strong> consultation:
                    </p>
                    <button className='abouts-btn mt-3'>Consult Our Experts <img src='/images/short-right.png' /></button>
                </div>
                <div className='col-lg-4 col-md-6'>
                    <h4 className='details-name'>
                        Mr. Balaji Kailasundaram
                    </h4>
                    <h5 className='details-position pt-2'>
                        Co-Founder
                    </h5>
                    <p className='details-contact'>
                        Email Address: <br/> <Link href='mailto:balaji@minitzon.com'>balaji@minitzon.com</Link>
                    </p>
                    <p className='details-contact'>
                        Phone Number: <br/> <Link href='tel:+917200841581'>(+91)-720-084-1581</Link>
                    </p>
                    <p className='details-socials'>
                    <Link href='#' target="_blank"><img className='social-icon' src='/images/facebook41.png' /></Link> <Link href='#' target="_blank"><img className='social-icon' src='/images/linkedin51.png'/></Link> <Link href='#' target="_blank"><img className='social-icon' src='/images/instagram41.png'/></Link> 
                    </p>
                </div>
            </div>
        </div>
      </section>
      <Footer />
</main>
</>
    )
}