import Head from "next/head";
import CountUp from "react-countup";
import { useEffect, useRef, useState } from "react";
import ScrollTrigger from "react-scroll-trigger";
import Link from "next/link";
import Image from "next/image";
import Button from "react-bootstrap/Button";
import Carousel from "react-bootstrap/Carousel";
import Stack from "react-bootstrap/Stack";
import { useForm } from "react-hook-form";
import axios from "axios";
import Footer from "../components/footer";
import { useRouter } from "next/router";
import HomeSlider from "../components/homeSlider";
import Card from "react-bootstrap/Card";
import ContactModal from "../components/ContactModal";
import ScrollSection from "../components/ScrollSection";

export default function Home() {
 

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
  } = useForm();

  const [selectedOption, setSelectedOption] = useState(0);

  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
    setValue("selectOption", event.target.value);
  };

  async function onSubmitForm(values) {
    let config = {
      method: "post",
      url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/contact`,
      headers: {
        "Content-Type": "application/json",
      },
      data: values,
    };

    try {
      const response = await axios(config);
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  const slides = [0, 1, 2];
  const [index, setIndex] = useState(0);
  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  const [counterOn, setCounterOn] = useState(false);

  return (
    <>
      <Head>
        <title>Minitzon Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon-min.ico" />
      </Head>
      <main>
        <HomeSlider />
        <ContactModal title = "Have A Project Idea ? Contact Us" />
        {/*Client Section */}
        <section id="client" className="client-section">
          <div className="container mt-5 clt-container ">
          <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> OUR CLIENTS </p>
              </div>
            </Stack>
            <div className="row pt-3">
              <div className="col-lg-6 col-md-6">
                <h2 className="client-title">
                  We're A Trusted Growth Partner
                </h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="cliented-text">
                  At Minitzon, there is continuous learning that happens as we
                  work on various projects. We also love to update and upgrade
                  with the latest innovations in the field of technology and
                  apps.
                </p>
              </div>
            </div>

            <div className="row client-row pt-3 text-center">
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/taxpare.png"
                    width={130}
                    height={31.1}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/transparent3x.png"
                    width={130}
                    height={33.35}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/ero.png"
                    width={120}
                    height={36.48}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/xaber-logo.png"
                    width={130}
                    height={35.54}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/Logo-Main.png"
                    width={120}
                    height={39.37}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/gobuzzr.png"
                    width={93.17}
                    height={39}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd">
                  <img
                    src="/minitzon-clients/ezyhelpers-logo.png"
                    width={172}
                    height={54}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/celeb_gap.png"
                    width={160}
                    height={34.29}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd1">
                  <img
                    src="/minitzon-clients/encompass-logo-regular 1.png"
                    width={120}
                    height={72.14}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/fisto.png"
                    width={110}
                    height={37.07}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/marc-shiparo.png"
                    width={164}
                    height={38.64}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg">
                  <img
                    src="/minitzon-clients/wood.png"
                    width={138}
                    height={42.71}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd2">
                  <img
                    src="/minitzon-clients/kariot-logo.png"
                    width={110}
                    height={52}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd3">
                  <img
                    src="/minitzon-clients/progreen.png"
                    width={130}
                    height={53.18}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd4">
                  <img
                    src="/minitzon-clients/Collision-Masters.png"
                    width={125}
                    height={70}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd5">
                  <img
                    src="/minitzon-clients/mocile.png"
                    width={106}
                    height={106}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd6">
                  <img
                    src="/minitzon-clients/progreen1.png"
                    width={138.81}
                    height={50}
                  />
                </div>
              </div>
              <div className="col-lg-2 col-md-3 col-6 client-col">
                <div className="card client-bg new-pd6">
                  <img
                    src="/minitzon-clients/housetoproofing1.png"
                    width={148}
                    height={50}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* About Section */}
        <section id="new-about">
          <div className="container nw-abt-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> WHO WE ARE </p>
              </div>
            </Stack>
            <div className="row">
              <div className="col-lg-4 col-md-6">
                <h3 className="client-abt-title pt-3">
                  We’re Experts at Helping Businesses reach their true potential
                </h3>
                <div className="card ab-card">
                  <h4 className="sim-heading">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <span>
                          <Image
                            src="/images/mission-new.png"
                            width={70}
                            height={75}
                            alt="Check Icon"
                            className="check-image"
                          />
                        </span>
                      </div>
                      <div className="col-lg-9 col-md-12 col-9">
                        <h4 className="nwabt-heading">
                          Mission -{" "}
                          <span style={{ color: "#6b738a" }}>
                            {" "}
                            Critical Digital Solutions For Complete Business
                            Transformation{" "}
                          </span>
                        </h4>
                      </div>
                    </div>
                  </h4>
                </div>
                <Link href="/aboutus" passHref>
                  <button className="abt-btn">
                    Explore More{" "}
                    <img src="/images/material-symbols_arrow-right-alt.png" />
                  </button>
                </Link>
              </div>
              <div className="col-lg-4 col-md-6 mbvl">
                <p className="abt-hero-para">
                  <strong>Transform your business processes</strong> by
                  migrating from legacy solution to
                  <strong> modern technology </strong> and development that
                  guarentee <strong>growth, optimization, </strong>
                  and <strong>ROI for your business</strong>
                </p>
                <p className="abt-hero-para">
                  Minitzon was founded at the right moment to meet the{" "}
                  <strong> challenges faced by business </strong> and
                  <strong>
                    {" "}
                    enable them to meet their digital transformation goals.{" "}
                  </strong>
                </p>
                <p className="abt-hero-para">
                  Established in 2020 in Chennai, Minitzon and its robust team
                  of{" "}
                  <strong>
                    {" "}
                    developers and consultants have provided Product Engineering
                    and Digital Transformation services
                  </strong>{" "}
                  to fortune
                  <strong>
                    {" "}
                    500 companies and start-up enterprises globally{" "}
                  </strong>
                </p>
              </div>
              <div className="col-lg-4 col-md-12">
                <ScrollTrigger
                  onEnter={() => setCounterOn(true)}
                  onExit={() => setCounterOn(false)}
                >
                  <div className="row tblt-dvc">
                    <div className="col-md-6">
                      <div className="card smp-card">
                        <div className="row">
                          <div className="col-lg-3 col-md-3 col-3">
                            <Image
                              src="/images/box-icon.png"
                              width={64}
                              height={64}
                              alt="Product Box Icon"
                              className="me-2 mt-3"
                            />
                          </div>
                          <div className="col-lg-9 col-md-9 col-9">
                            <h2 className="nwabt-car-heading">
                              {counterOn && (
                                <CountUp
                                  start={0}
                                  end={30}
                                  duration={2}
                                  delay={0}
                                />
                              )}
                              <span>+</span>
                            </h2>
                            <h3 className="abt-car-para">
                              {" "}
                              Web & Mobile Products{" "}
                            </h3>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="card smp-card mt-3">
                        <div className="row">
                          <div className="col-lg-3 col-md-3 col-3">
                            <Image
                              src="/images/cstmr-icon.png"
                              width={64}
                              height={64}
                              alt="Users Icon"
                              className="me-2 mt-2"
                            />
                          </div>
                          <div className="col-lg-9 col-md-9 col-9">
                            <h2 className="nwabt-car-heading">
                              {counterOn && (
                                <CountUp
                                  start={0}
                                  end={2000}
                                  duration={2}
                                  delay={0}
                                />
                              )}
                              <span> + </span>
                            </h2>
                            <h3 className="abt-car-para">
                              {" "}
                              Million Users Touched
                            </h3>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="card smp-card mt-3">
                        <div className="row">
                          <div className="col-lg-3 col-md-3 col-3">
                            <Image
                              src="/images/rckt-icon.png"
                              width={64}
                              height={64}
                              alt="Rocket Launch Icon"
                              className="me-2 mt-2"
                            />
                          </div>
                          <div className="col-lg-9 col-md-9 col-9">
                            <h2 className="nwabt-car-heading">
                              {counterOn && (
                                <CountUp
                                  start={0}
                                  end={110}
                                  duration={2}
                                  delay={0}
                                />
                              )}
                              <span>+</span>
                            </h2>
                            <h3 className="abt-car-para"> Project Launched</h3>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="card smp-card mt-3">
                        <div className="row">
                          <div className="col-lg-3 col-md-3 col-3">
                            <Image
                              src="/images/threestar.png"
                              width={64}
                              height={64}
                              alt="Customer Review Icon"
                              className="me-2 mt-2"
                            />
                          </div>
                          <div className="col-lg-9 col-md-9 col-9">
                            <h2 className="nwabt-car-heading">
                              {counterOn && (
                                <CountUp
                                  start={0}
                                  end={100}
                                  duration={2}
                                  delay={0}
                                />
                              )}
                              <span>%</span>
                            </h2>
                            <h3 className="abt-car-para">
                              {" "}
                              Customer Satisfication{" "}
                            </h3>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card tbd">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/box-icon.png"
                          width={64}
                          height={64}
                          alt="Product Box Icon"
                          className="me-2 mt-3"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="nwabt-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={30}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>+</span>
                        </h2>
                        <h3 className="abt-car-para">
                          {" "}
                          Web & Mobile Products{" "}
                        </h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card tbd mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/cstmr-icon.png"
                          width={64}
                          height={64}
                          alt="Users Icon"
                          className="me-2 mt-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="nwabt-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={2000}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span> + </span>
                        </h2>
                        <h3 className="abt-car-para"> Million Users Touched</h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card tbd mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/rckt-icon.png"
                          width={64}
                          height={64}
                          alt="Rocket Launch Icon"
                          className="me-2 mt-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="nwabt-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={110}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>+</span>
                        </h2>
                        <h3 className="abt-car-para"> Project Launched</h3>
                      </div>
                    </div>
                  </div>
                  <div className="card smp-card tbd mt-3">
                    <div className="row">
                      <div className="col-lg-3 col-md-3 col-3">
                        <Image
                          src="/images/threestar.png"
                          width={64}
                          height={64}
                          alt="Customer Review Icon"
                          className="me-2 mt-2"
                        />
                      </div>
                      <div className="col-lg-9 col-md-9 col-9">
                        <h2 className="nwabt-car-heading">
                          {counterOn && (
                            <CountUp
                              start={0}
                              end={100}
                              duration={2}
                              delay={0}
                            />
                          )}
                          <span>%</span>
                        </h2>
                        <h3 className="abt-car-para">
                          {" "}
                          Customer Satisfication{" "}
                        </h3>
                      </div>
                    </div>
                  </div>
                </ScrollTrigger>
              </div>
            </div>
            <div className="nwd-image">
              <Image
                src="/images/bullseye.webp"
                width={1340}
                height={754}
                alt="Team discussing Image"
              />
            </div>
          </div>
        </section>

        <section id="recent-works">
          <div className="container new-ds">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> CASE STUDIES </p>
              </div>
            </Stack>
            <div className="row pt-4">
              <div className="col-lg-3 col-md-3">
                <h2 className="case-heading">Our Recent Works</h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="case-para">
                  In 6 years we have completed more than 200 individual projects
                  to develop modern websites, web and mobile applications for
                  clients from all over the world.
                </p>
              </div>
              <div className="col-lg-3 col-md-3">
                <Link href="/portfolio" passHref>
                  <button className="about-btn">
                    View All Cases{" "}
                    <img src="/images/material-symbols_arrow-right-alt.png" />
                  </button>
                </Link>
              </div>
            </div>
          </div>
          <ScrollSection />
        </section>
        

        {/*CTA Section */}
        <section className="hm-sec-cta">
          <div className="container">
            <Card className="home-cta my-5">
              <Card.Body>
                <div className="row">
                  <div className="col-lg-7 col-md-7 col-12">
                    <Stack direction="horizontal">
                      <div className=" badge-abot-btn">
                        <img
                          src="/images/Rectangle-kariot.png"
                          className="me-2"
                          alt="design-dot"
                        />
                        <p> GET INTO TOUCH </p>
                      </div>
                    </Stack>
                    <h2 className="homcta-heading pt-2">
                      Have a project? We would love to help.
                    </h2>
                    <p className="hmcta-para">
                      Reach out to us to identify business challenges and get
                      efficient digital solutions.
                    </p>
                    <Link href="/contact-us" passHref>
                      <button className="about-btn mt-3">
                        Get Started{" "}
                        <img src="/images/material-symbols_arrow-right-alt.png" />
                      </button>
                    </Link>
                  </div>
                  <div className="col-lg-5 col-md-5">
                    <Image
                      src="/images/homecta.webp"
                      width={640}
                      height={660}
                      alt="Chat with our expert "
                      className="hmcta-image"
                    />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </div>
        </section>

        {/*Service Section */}

        <section id="services">
          <div className="container service-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> WHAT WE DO </p>
              </div>
            </Stack>
            <div className="row  pt-4">
              <div className="col-lg-6 col-md-6">
                <h2 className="service-heading pb-1">
                  We Pride Ourselves On Being The One Stop Shop For All Your
                  Needs.
                </h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="service-para pb-3">
                  We envision, design, build and support solutions that
                  transform and elevate your digital presence. Our expertise
                  extends to clients worldwide enabling them to achieve global
                  recognition and standard.
                </p>
              </div>
            </div>
            <div className="row">
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/app-development.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="App Development icon"
                    />
                    <h3 className="qs-card-heading">Mobile App Development</h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/mobile-app" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/backend.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Web Development icon"
                    />
                    <h3 className="qs-card-heading">Website Development</h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/web-development" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/cloud-computing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Cloud Computing icon"
                    />
                    <h3 className="qs-card-heading">Cloud Computing </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/cloud-consulting-services" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/devops.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="DevOps icon"
                    />
                    <h3 className="qs-card-heading">
                      DevOps Consulting Services{" "}
                    </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/devops-consulting-service" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/digital-marketing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Digital Marketing icon"
                    />
                    <h3 className="qs-card-heading"> Digital Marketing </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="#" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-6 pt-3">
                <Card className="hm-customize-card">
                  <Card.Body
                    style={{ paddingRight: "0px", paddingLeft: "0px" }}
                  >
                    <Image
                      src="/images/testing.png"
                      width={80}
                      height={80}
                      className="do-icon pb-3"
                      alt="Quality engineering and testing icon"
                    />
                    <h3 className="asd-card-heading">
                      {" "}
                      Quality Engineering & Testing{" "}
                    </h3>
                    <p className="qsd-para">
                      Minitzon, one of the top blockchain development companies
                      in India, offers end-to-end Blockchain software
                      Development services that are robust and reliable. We are
                      enablers that help you achieve transparency best-in-class
                      full-stack blockchain developer experts.
                    </p>
                    <Link href="/quality-engineering-testing" passHref>
                      <Image
                        src="/images/Group2495.png"
                        width={56}
                        height={56}
                        className="do-btn-icon"
                        alt="button-icon"
                      />
                    </Link>
                  </Card.Body>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section id="why-mnt">
          <div className="container mnt-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> WHY MINITZON </p>
              </div>
            </Stack>
            <div className="row pt-4">
              <div className="col-lg-6 col-md-6">
                <h2 className="service-heading pb-1">
                  We're Always Looking For New Ideas For 360° Digital Solutions!
                </h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="abot-hero-para">
                  <strong>As technopreneurs</strong> and
                  <strong>
                    {" "}
                    pioneers of 360° digital solutions, we are always on the
                    lookout for new ideas !{" "}
                  </strong>{" "}
                  we love to collaborate with{" "}
                  <strong>new age businesses </strong> that look at delivering
                  <strong> innovative solution </strong> coupled with the{" "}
                  <strong> latest technology </strong>
                </p>
              </div>
            </div>
            <Carousel
              className="hm-car"
              animation="fade"
              prevIcon={
                <img
                  src="/images/arrow-left.png"
                  className="previoushm-icon"
                  alt="Previous"
                />
              }
              nextIcon={
                <img
                  src="/images/arrowblack.png"
                  className="nexthm-icon"
                  alt="Next"
                />
              }
              interval={null}
              activeIndex={index}
              onSelect={handleSelect}
              indicators={false}
            >
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/group-icon.png"
                        width={50}
                        height={50}
                        alt="Group Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Diversed Portfolio of Clients
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/expert-icon.png"
                        width={50}
                        height={50}
                        alt="Expertise Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">Expertise</h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/solution.png"
                        width={50}
                        height={50}
                        alt="Ideas Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Flexible & Customized Solution
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/selection.png"
                        width={50}
                        height={50}
                        alt="Slection check Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Everything In-House
                      </h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/group-icon.png"
                        width={50}
                        height={50}
                        alt="Group Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Diversed Portfolio of Clients
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/expert-icon.png"
                        width={50}
                        height={50}
                        alt="Expertise Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">Expertise</h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/solution.png"
                        width={50}
                        height={50}
                        alt="Ideas Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Flexible & Customized Solution
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/selection.png"
                        width={50}
                        height={50}
                        alt="Slection check Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Everything In-House
                      </h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/group-icon.png"
                        width={50}
                        height={50}
                        alt="Group Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Diversed Portfolio of Clients
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/expert-icon.png"
                        width={50}
                        height={50}
                        alt="Expertise Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">Expertise</h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card tbt">
                      <Image
                        src="/images/solution.png"
                        width={50}
                        height={50}
                        alt="Ideas Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Flexible & Customized Solution
                      </h4>
                      <p className="carels-para">
                        From startups to corporates, Minitzon has partnered with
                        every business to provide customized and highly
                        effective solutions.
                      </p>
                    </Card>
                  </div>
                  <div className="col-lg-3 col-md-6 my-3">
                    <Card className="hm-card">
                      <Image
                        src="/images/selection.png"
                        width={50}
                        height={50}
                        alt="Slection check Icon"
                        className="grp"
                      />
                      <h4 className="hmcard-heading pt-3">
                        Everything In-House
                      </h4>
                      <p className="carels-para">
                        We have experience and the expertise in delivering
                        end-to-end solutions, right form conceiving an idea to
                        providing the technological support to businesses
                        globally.
                      </p>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
            </Carousel>
          </div>
        </section>

        <section id="stage-modal">
          <div className="container new-ds">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> FIVE STAGES </p>
              </div>
            </Stack>
            <div className="row pt-4">
              <div className="col-lg-4 col-md-4">
                <h2 className="case-heading">The 5 Stage Modal We Work On</h2>
              </div>
              <div className="col-lg-4 col-md-4">
                <p className="case-para">
                  Duis aute irure dolor in reprehenderit in voluptate velit esse
                  cillum dolore eu fugiat nulla pariatur.
                </p>
              </div>
              <div className="col-lg-4 col-md-4">
                <Button href="/portfolio" className="cntct-btn">
                  <p>look at our</p> <h6>Case Studies</h6>{" "}
                </Button>
              </div>
            </div>
            <div className="img-containers">
              <img src="/images/5stages.svg" />
            </div>
          </div>
        </section>

        <section id="testimonials" className="my-4 py-4">
          <div className="container testimonial-container">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> TESTIMONIALS </p>
              </div>
            </Stack>
            <div className="row py-4">
              <div className="col-lg-6 col-md-6">
                <h3 className="tst-heading">
                  What Clients are Saying About Our Collaboration
                </h3>
              </div>
            </div>
            <Carousel
              className="hm-cars"
              animation="fade"
              prevIcon={
                <img
                  src="/images/newarleft.png"
                  width={58}
                  className="previousdm-icon"
                  alt="Previous"
                />
              }
              nextIcon={
                <img
                  src="/images/newarrow.png"
                  width={58}
                  className="nextdm-icon"
                  alt="Next"
                />
              }
              interval={null}
              activeIndex={index}
              onSelect={handleSelect}
              indicators={false}
            >
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="row">
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                  <div className="col-lg-6 col-md-6 mt-3">
                    <Card className="dm-customize-card">
                      <Card.Body
                        style={{ paddingRight: "0px", paddingLeft: "0px" }}
                      >
                        <div className="cl-container">
                          <div className="row" style={{ alignItems: "center" }}>
                            <div className="col-lg-3 col-md-3 col-3">
                              <Image
                                src="/images/client.webp"
                                width={120}
                                height={120}
                                className="client-icon pb-3"
                                alt="Client Icon"
                              />
                            </div>
                            <div
                              className="col-lg-7 col-md-6 col-6"
                              style={{
                                paddingLeft: "0px",
                                paddingRight: "0px",
                              }}
                            >
                              <h3 className="dm-card-heading">
                                Kalyan Krishnamurthy,
                                <br />
                                <span className="txt">CEO at Flipkart</span>
                              </h3>
                            </div>
                            <div className="col-lg-2 col-md-3 col-3">
                              <span className="lnkimg">
                                <Image
                                  src="/images/bi_linkedin.png"
                                  width={30}
                                  height={30}
                                  alt="Linkedin Icon image"
                                />
                              </span>
                            </div>
                          </div>
                        </div>

                        <blockquote className="test-text align-middle card-row">
                          It's a big team and what's really good is that it's a
                          specialized team, so that means they have to be the
                          best at what they do. I am very happy and impressed.
                        </blockquote>
                      </Card.Body>
                    </Card>
                  </div>
                </div>
              </Carousel.Item>
            </Carousel>
          </div>
        </section>

        <section id="contact" className="my-4 py-4">
          <div className="container contact-container">
            <div className="row py-2">
              <Stack direction="horizontal">
                <div className=" badge-abot-btn">
                  <img
                    src="/images/Rectangle-kariot.png"
                    className="me-2"
                    alt="design-dot"
                  />
                  <p> GET INTO TOUCH </p>
                </div>
              </Stack>
            </div>
            <div className="row">
              <div className="col-lg-8 col-md-8">
                <h2 className="contact-heading">
                  Hello! Let's make great work together.{" "}
                  <span> &#129304; </span>{" "}
                </h2>
                <p className="contact-text">
                  Take your startup to the next level. Our process revolves
                  around your unique business needs.
                </p>
              </div>
              <div className="col-lg-4 col-md-4">
                <Button href="/portfolio" className="cntct-btn">
                  <p>look at our</p> <h6>Case Studies</h6>{" "}
                </Button>
              </div>
            </div>
            <div className="row mt-5">
              <div className="col-lg-4 col-md-4">
                <h2 className="contct-heading">Hey! Got a startup idea?</h2>
                <p className="contct-para">
                  Let us give you our honest opinion. Book your{" "}
                  <strong style={{ color: "#1e2436" }}> FREE 30-Minute </strong>{" "}
                  consultation:
                </p>
                <div className="card contct-card">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/contact-us-mail.png"
                        width={50}
                        height={50}
                        alt="Contact us mail icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-10">
                      <p className="lets-para mb-0">Let's talk</p>
                      <Link href="/contact-us" className="lets-link">
                        Consult Our Experts
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Balaji Kailasasundaram
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person1.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Karthick Ganesan
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card contct-card mt-4">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/mailer-icon.png"
                        width={50}
                        height={50}
                        alt="Mailer icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-9">
                      <p className="lets-para mb-0">Send us an email</p>
                      <Link
                        href="mailto:contact@trimsel.com"
                        className="lets-link"
                      >
                        contact@trimsel.com
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-8 col-md-8">
                <div className="card ntoct-card">
                  <h3 className="stages-heading">Have an idea?</h3>
                  <h3 className="cntoct-heading">Let's get in touch</h3>

                  <form id="home-form" onSubmit={handleSubmit(onSubmitForm)}>
                    <p className="mt-5 form-lbl-para"> I'm intrested in :</p>
                    <div className="options">
                      <input
                        {...register("product")}
                        type="radio"
                        name="selectOption"
                        value="Product Development"
                        id="product"
                        checked={selectedOption === "Product Development"}
                        onChange={handleOptionChange}
                        className="form-control"
                        placeholder="product"
                      />
                      <label
                        htmlFor="product"
                        className="abot-radio-style mt-3"
                      >
                        Product Development
                      </label>

                      <input
                        {...register("mobile-app")}
                        type="radio"
                        name="selectOption"
                        value="Mobile App Development"
                        id="mobile-app"
                        checked={selectedOption === "Mobile App Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="mobile-app"
                        className="abot-radio-style mt-3"
                      >
                        Mobile App Development
                      </label>

                      <input
                        {...register("cloud-devops")}
                        type="radio"
                        name="selectOption"
                        value="Cloud and DevOps"
                        id="cloud-devops"
                        checked={selectedOption === "Cloud and DevOps"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="cloud-devops"
                        className="abot-radio-style mt-3"
                      >
                        Cloud & DevOps
                      </label>
                      <input
                        {...register("website-development")}
                        type="radio"
                        name="selectOption"
                        value="Website Development"
                        id="website-development"
                        checked={selectedOption === "Website Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="website-development"
                        className="mt-3 abot-radio-style"
                      >
                        Website Development
                      </label>
                      <input
                        {...register("digital-marketing")}
                        type="radio"
                        name="selectOption"
                        value="Digital Marketing"
                        id="digital-marketing"
                        checked={selectedOption === "Digital Marketing"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="digital-marketing"
                        className="mt-3 abot-radio-style"
                      >
                        Digital Marketing
                      </label>
                      <input
                        {...register("blockchain-development")}
                        type="radio"
                        name="selectOption"
                        value="Blockchain Development"
                        id="blockchain-development"
                        checked={selectedOption === "Blockchain Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="blockchain-development"
                        className="mt-3 abot-radio-style"
                      >
                        Block Chain Development
                      </label>
                      <input
                        {...register("quality-testing")}
                        type="radio"
                        name="selectOption"
                        value="Quality Engineering and Technology"
                        id="quality-testing"
                        checked={
                          selectedOption ===
                          "Quality Engineering and Technology"
                        }
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="quality-testing"
                        className="mt-3 abot-radio-style"
                      >
                        Quality Engineering & Technology
                      </label>
                      <input
                        {...register("other")}
                        type="radio"
                        name="selectOption"
                        value="Other"
                        id="other"
                        checked={selectedOption === "Other"}
                        onChange={handleOptionChange}
                      />
                      <label htmlFor="other" className="mt-3 abot-radio-style">
                        Other
                      </label>
                    </div>
                    <div className="row py-3">
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("name", {
                              required: {
                                value: true,
                                message: "Your name is required",
                              },
                            })}
                            type="text"
                            id="name"
                            name="name"
                            className="form-control abot-form"
                            placeholder="Full Name*"
                          />
                          <span className="error-design pt-3">
                            {errors?.name?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("phone", {
                              required: {
                                value: true,
                                message: "Your phone number is required",
                              },
                              minLength: {
                                value: 10,
                                message: "Enter a valid mobile number",
                              },
                              maxLength: {
                                value: 11,
                                message: "Enter a valid mobile number",
                              },
                            })}
                            type="tel"
                            name="phone"
                            id="phone"
                            className="form-control abot-form"
                            placeholder="Mobile Number*"
                          />
                          <span className="error-design pt-3">
                            {errors?.phone?.message}
                            {errors?.phone?.maxLength?.message}
                            {errors?.phone?.minLength?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("email", {
                              required: {
                                value: true,
                                message: "Email id is required",
                              },
                              pattern: {
                                value:
                                  /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
                                message: "Enter a valid email address",
                              },
                            })}
                            type="email"
                            name="email"
                            id="email"
                            className="form-control abot-form"
                            placeholder="Email*"
                          />
                          <span className="error-design pt-3">
                            {errors?.email?.message}
                            {errors?.email?.pattern?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("skype")}
                            type="text"
                            name="skype"
                            id="skype"
                            className="form-control abot-form"
                            placeholder="SkypeID"
                          />
                        </div>
                      </div>
                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("company")}
                            type="text"
                            name="company"
                            id="company"
                            className="form-control abot-form"
                            placeholder="Company"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <textarea
                            {...register("message")}
                            type="textarea"
                            name="message"
                            id="message"
                            className="form-control  abot-form"
                            placeholder="Your Message"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="text-right text-md-end">
                          <input type="submit" className="sbmt-btn" />
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="blog" className="py-4">
          <div className="container blog-container">
            <div className="row py-3">
              <Stack direction="horizontal">
                <div className=" badge-abot-btn">
                  <img
                    src="/images/Rectangle-kariot.png"
                    className="me-2"
                    alt="design-dot"
                  />
                  <p> <b> OUR BLOGS </b> </p>
                </div>
              </Stack>
              <div className="col-lg-5 col-md-5 py-4">
                <h2 className="contacts-heading">
                  Read Our Latest Blogs and News
                </h2>
              </div>
              <div className="col-lg-7 col-md-7 py-4">
                <p className="blog-para">
                  At Minitzon, there is continuous learning that happens as we
                  work on various projects. We also love to update and upgrade
                  with the latest innovations in the field of technology and
                  apps.
                </p>
              </div>
            </div>
            <div className="row no-gutters">
              <div className="col-lg-6">
                <div className="card blog-card">
                  <div className="row no-gutters">
                    <div className="col-lg-5 col-md-5 py-3">
                      <img
                        className="card-img"
                        src="/images/blog-img.png"
                        alt=""
                      />
                    </div>
                    <div className="col-lg-7 col-md-7">
                      <Button className="card-badge mb-2">Development</Button>
                      <h5 className="blog-card-title">
                        Top 10 Mobile App Development Frameworks in 2023
                      </h5>
                      <p className="blog-card-para">
                        We've entered on age where our lives are...{" "}
                        <Link href="#">Read More</Link>
                      </p>
                    </div>
                  </div>
                  <div className="row no-gutters">
                    <div className="col-lg-5 col-md-5 py-3">
                      <img
                        className="card-img"
                        src="/images/blogs-img.png"
                        alt=""
                      />
                    </div>
                    <div className="col-lg-7 col-md-7 py-3">
                      <Button className="card-badge mb-2">Development</Button>
                      <h5 className="blog-card-title">
                        Top 10 Mobile App Development Frameworks in 2023
                      </h5>
                      <p className="blog-card-para">
                        We've entered on age where our lives are...{" "}
                        <Link href="#">Read More</Link>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-6">
                <div className="card blog-card">
                  <div className="card-image">
                    <img className="blog-image" src="/images/blog-image.png" />
                  </div>
                  <div className="card-content">
                    <Button className="card-badge my-2">Development</Button>
                    <h5 className="blogs-card-title">
                      How hybrid app development can help you build custom apps
                    </h5>
                    <p className="blog-card-para">
                      Digitization has taken over every industry and business
                      aspect. The pandemic only fuelled our shift tower...
                      <Link href="#">Read More</Link>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <Footer />
      </main>
    </>
  );
}
