import Head from "next/head";
import Link from "next/link";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import Stack from "react-bootstrap/Stack";
import Image from "next/image";
import Accordion from "react-bootstrap/Accordion";
import ListGroup from "react-bootstrap/ListGroup";
import Header from "../components/header";
import Footer from "../components/footer";
import TestimonialClient from "../components/testimonial";
import ClientLogo from "../components/clientLogo";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import CarouselComponent from "../components/carouselComponent";
import { useState } from "react";
import { useForm } from "react-hook-form";
import axios from "axios";
import { FaRegEnvelope } from "@react-icons/all-files/fa/FaRegEnvelope";
import { FaLongArrowAltRight } from "@react-icons/all-files/fa/FaLongArrowAltRight";
import ContactModal from "../components/ContactModal";
import Table from "react-bootstrap/Table";

export default function mobileApp() {
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
  } = useForm();

  const [selectedOption, setSelectedOption] = useState(0);

  const handleOptionChange = (event) => {
    setSelectedOption(event.target.value);
    setValue("selectOption", event.target.value);
  };

  async function onSubmitForm(values) {
    let config = {
      method: "post",
      url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/contact`,
      headers: {
        "Content-Type": "application/json",
      },
      data: values,
    };

    try {
      const response = await axios(config);
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  const slides = [1, 2, 3];
  const [index, setIndex] = useState(0);
  const handleSelect = (selectedIndex, e) => {
    setIndex(selectedIndex);
  };

  return (
    <>
      <Head>
        <title>Mobile App Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon-min.ico" />
      </Head>
      <main>
        <section className="hero-mbl">
          <Header />
          <section className="hero">
            <div className="container pt-3 pb-5">
              <div id="app" className="new-mbls">
                <div className="title">
                  <div className="title-inner">
                    <div className="cafe">
                      <p className="breadcrumbs">
                        <Link href="#">Home</Link> <span> &#x2027; </span>{" "}
                        <Link href="#">Services</Link> <span> &#x2027; </span>{" "}
                        Mobile App Development
                      </p>

                      <div className="cafe-inner new-title">
                        <h1>
                          {" "}
                          Build Compelling Apps That Fit Your Business Needs
                        </h1>
                      </div>
                    </div>
                    <div className="mozart">
                      <div className="mozart-inner">
                        <p>
                          Minitzon is one of the top mobile app development
                          companies in India that empowers your enterprise with
                          leading technology and modern mobile application
                          solutions.
                        </p>
                      </div>
                    </div>
                    <div className="mozart">
                      <div className="mozart-inner">
                        <Link href="/contact-us" passHref>
                          <button className="btn btn-primary get-btn">
                            Get Started Today{" "}
                            <img src="/images/material-symbols_arrow-right-alt.png" />
                          </button>
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="imgr">
                  <Image
                    src="/images/mobilehero.webp"
                    className="hero-imgs"
                    width={637}
                    height={666}
                    alt="Mobile App Development Hero Image"
                  />
                </div>
              </div>
            </div>
          </section>
        </section>

        <section id="about-mbl">
          <div className="container mbl-about">
            <div className="row mbl-abt">
              <div className="col-lg-9 col-md-9">
                <Stack direction="horizontal" className="pb-4">
                  <div className=" badge-abot-btn">
                    <img
                      src="/images/Rectangle-kariot.png"
                      className="me-2"
                      alt="design-dot"
                    />
                    <p> WHO WE ARE </p>
                  </div>
                </Stack>
                <h2 className="about-head">
                  Mobile App Development Company in Chennai
                </h2>
              </div>
              <div className="col-lg-3 col-md-3">
                <Image
                  src="/images/Group306.png"
                  className="mdl-btn"
                  alt="Lets talk image"
                  width={160}
                  height={160}
                />
              </div>
            </div>
            <p className="abt-desc">
              Mobile apps are changing the way businesses engage with their
              customers, vendors, and employees. Minitzon is one of the top
              mobile app development companies in India that empowers your
              enterprise with leading technology and modern mobile application
              solutions. We are a team of collaborative developers with industry
              knowledge and skill that works together to help companies make
              long strides toward their digital and customer experience goals.
            </p>
            <p className="abt-desc">
              As an app development company in Chennai, we understand niche
              segments and their behaviors to use them in our app development
              strategies. This helps us see maximum success in our products with
              the highest customer experience ratings.
            </p>
            <p className="abt-desc">
              Our mobile app development services in India extend to
              custom-built apps for Android and iOS platforms with ML and AI
              Applications for maximum customer satisfaction. Our efforts to
              meet client requirements with the top mobile app development
              services in Chennai have brought us a reputation and
              acknowledgment as a trusted brand for mobile app development in
              India.
            </p>
          </div>
        </section>

        <section id="digital-mbl">
          <div className="container">
            <div className="row">
              <div className="col-lg-6 col-md-6">
                <h3 className="dgt-heading">Expand Your Digital Platform</h3>
                <p className="dgt-para pt-1">
                  See how Minitzone, the leading mobile app development company
                  in India can help you business grow.
                </p>
              </div>
              <div className="col-lg-6 col-md-6">
                <Button className="dgt-btn" href="#">
                  <img src="/images/Group309.png" width={40} /> Your deadlines
                  are our goals
                </Button>
              </div>
            </div>
            <div className="row pt-5">
              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <img src="/images/like1.png" /> Reliable Quality
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <Image
                      src="/images/profits.png"
                      width={40}
                      height={40}
                      alt="Profit Icon"
                    />{" "}
                    Cost Efficient
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <img src="/images/guru1.png" /> Build By Experts
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <img src="/images/ethics1.png" /> Transparent Process
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>

              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <img src="/images/customer1.png" /> Customer Engagement
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>
              <div className="col-lg-4 col-md-4">
                <Card className="mbl-card">
                  <Card.Title className="title-dsgn">
                    <img src="/images/time1.png" /> Quick Time To Market
                  </Card.Title>
                  <Card.Body>
                    <p className="card-para">
                      What makes Minitzon the top Mobile app development company
                      is our keen attention to detail and grade-A product
                      deliveries.
                    </p>
                  </Card.Body>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section id="help-mbl">
          <div className="container hlp-container">
            <div className="row helper-row">
              <div className="col-lg-6 col-md-6">
                <h3 className="helper-title">How we can help you?</h3>
                <p className="helper-para">
                  With our amazing in-house talent, we deliver insightful
                  solutions You can see a seamless transition of your business
                  to the digital era.
                </p>
                <img src="/images/beatsnoop4.png" className="helper-image" />
              </div>
              <div className="col-lg-6 col-md-6">
                <ListGroup className="helper-list-group">
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2">
                        <span className="list-icon">
                          <img src="/images/Group2539.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-column">
                        Validate your vision and provide a clear roadmap
                      </div>
                    </div>
                  </ListGroup.Item>
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2">
                        <span className="list-icon">
                          <img src="/images/Group2538.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-column">
                        Innovative solutions for complex problems
                      </div>
                    </div>
                  </ListGroup.Item>
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2">
                        <span className="list-icon">
                          <img src="/images/Group2540.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-column">
                        Deliver products at 10x speed and maximize efficiency
                      </div>
                    </div>
                  </ListGroup.Item>
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2">
                        <span className="list-icon">
                          <img src="/images/Group2541.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-columns">
                        Adapt to the latest technologies and provide a
                        future-proof product
                      </div>
                    </div>
                  </ListGroup.Item>
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2">
                        <span className="list-icon">
                          <img src="/images/Group2542.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-column">
                        Ensure product scalability, security, and modularity
                      </div>
                    </div>
                  </ListGroup.Item>
                  <ListGroup.Item className="helper-list-item mt-3">
                    <div className="row">
                      <div className="col-lg-2 col-md-2 col-2 ">
                        <span className="list-icon">
                          <img src="/images/Group2543.png" />
                        </span>
                      </div>
                      <div className="col-lg-10 col-md-10 col-10 helper-list-column">
                        World-class support during and after project completion
                      </div>
                    </div>
                  </ListGroup.Item>
                </ListGroup>
              </div>
            </div>
          </div>
        </section>

        {/*Mobile App Service Section*/}
        <section id="mobile-services">
          <div className="container service-container">
            <div className="row">
              <Stack direction="horizontal" className="pb-4">
                <div className=" badge-abot-btn">
                  <img
                    src="/images/Rectangle-kariot.png"
                    className="me-2"
                    alt="design-dot"
                  />
                  <p> WHAT WE DO </p>
                </div>
              </Stack>
              <div className="col-lg-5">
                <h2 className="service-heading">
                  Our Mobile App Development Services
                </h2>
              </div>
              <div className="col-lg-7">
                <p className="service-mobile-para pb-3">
                  Mobile apps are a crucial part of a business in today’s
                  digital world. Our end-to-end mobile app development services
                  can give you a competitive edge in the market all under one
                  roof.
                </p>
              </div>
            </div>
          </div>

          <section id="services-list">
            <div className="container servicelist-container">
              <div className="row">
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group322.png" />
                      </div>
                      <div className="service-card-title pt-4 pb-2">
                        <h3>Mobile App Design</h3>
                      </div>
                      <div className="card-text service-card-text pb-3">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated.
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group323.png" />
                      </div>
                      <div className="service-card-title pt-4 pb-2">
                        <h3>iOS App Development</h3>
                      </div>
                      <div className="card-text service-card-text pb-3">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated..
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group324.png" />
                      </div>
                      <div className="service-mobile-card-title pt-4 pb-2">
                        <h3>Android App Development</h3>
                      </div>
                      <div className="card-text service-card-text pb-3">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated.
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group325.png" />
                      </div>
                      <div className="service-card-title pt-4 pb-2">
                        <h3>Hybrid App Development</h3>
                      </div>
                      <div className="card-text service-card-text pb-1">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated.
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group326.png" />
                      </div>
                      <div className="service-card-title pt-4 pb-2">
                        <h3 className="dff">Mobile App Testing</h3>
                      </div>
                      <div className="card-text service-card-text pb-3">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated.
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4 col-md-6 mt-4">
                  <div className="card service-mobile-card">
                    <div className="card-body">
                      <div className="card-images">
                        <img src="/images/Group327.png" />
                      </div>
                      <div className="service-card-title pt-4 pb-2">
                        <h3>24*7 Maintenance & Support</h3>
                      </div>
                      <div className="card-text service-card-text pb-3">
                        <p>
                          We ensure to use guidelines by Apple and Google to
                          make our apps visually appealing while keeping all
                          functionalities tightly integrated.
                        </p>
                      </div>
                      <div className="card-link">
                        <Link className="explore-link" href="#">
                          Explore More <FaLongArrowAltRight />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="container process-container">
              <div className="row py-5">
                <Stack direction="horizontal" className="pb-4">
                  <div className=" badge-abot-btn">
                    <img
                      src="/images/Rectangle-kariot.png"
                      className="me-2"
                      alt="design-dot"
                    />
                    <p> DEVELOPMENT PROCESS </p>
                  </div>
                </Stack>
                <div className="col-lg-4 col-md-4">
                  <h3 className="process-heading">
                    Our Mobile App Development Process
                  </h3>
                </div>
                <div className="col-lg-5 col-md-5">
                  <p className="process-para">
                    We ensure that our customers experience a transparent and
                    seamless process throughout the development journey
                  </p>
                </div>
                <div className="col-lg-3 col-md-3">
                  <Link href="/portfolio" passHref>
                    <Button className="process-btn">
                      <p>look at our</p> <h6>Case Studies</h6>{" "}
                    </Button>
                  </Link>
                </div>
              </div>
              <Image
                src="/images/processimg.webp"
                width={1116}
                height={725}
                alt="Process Image"
                className="prcimg"
              />
            </div>
          </section>
        </section>

        <section className="pm-sec-cta">
          <div className="container">
            <Card className="port-cta my-5">
              <Card.Body>
                <div className="row">
                  <div className="col-lg-7 col-md-7 col-12">
                    <Stack direction="horizontal">
                      <div className=" badge-abot-btn">
                        <img
                          src="/images/Rectangle-kariot.png"
                          className="me-2"
                          alt="design-dot"
                        />
                        <p> GET INTO TOUCH </p>
                      </div>
                    </Stack>
                    <h2 className="homcta-heading pt-2">
                      Wanna Develop a Mobile Application? Contact Us Now!
                    </h2>
                    <p className="hmcta-para">
                      Reach out to us to identify business challenges and get
                      efficient digital solutions.
                    </p>
                    <Link href="/contact-us" passHref>
                      <button className="portcta-btn mt-3">
                        <FaRegEnvelope className="me-2" /> Get In Touch{" "}
                      </button>
                    </Link>
                  </div>
                  <div className="col-lg-5 col-md-5">
                    <Image
                      src="/images/ctambbg.webp"
                      width={600}
                      height={598}
                      alt="Chat with our expert "
                      className="hmcta-image"
                    />
                  </div>
                </div>
              </Card.Body>
            </Card>
          </div>
        </section>

        <section className="mbl-tools">
          <div className="container mbltool-container">
            <Row>
              <Col lg={6} md={6}>
                <h3 className="tools-heading">
                  Mobile App Tools And Technology Stack
                </h3>
              </Col>
              <Col lg={6} md={6}>
                <p className="tools-para">
                  The key to success for a successful DevOps transformation is
                  scaling your systems and digital business vulnerability. We
                  are DevOps tools and platforms Use for successful DevOps
                  implementation:
                </p>
              </Col>
            </Row>
            <Row className="mt-4">
              <Col lg={3} md={6} xs={6} className="mb-3">
                <h4 className="tools-title"> iOS </h4>
                <Table className="mb-3" style={{ width: "fit-content" }}>
                  <tbody>
                    <tr>
                      <td className="new-bdr">
                        <Image
                          src="/images/Swift_logo.png"
                          width={110}
                          height={34}
                          alt="Swift iOS Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                      <td className="new-bdr d-none d-lg-table-cell">
                        <Image
                          src="/images/obj-c.png"
                          width={120}
                          height={41}
                          alt="Objective-C iOS Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td className="d-lg-none new-bdr">
                        <Image
                          src="/images/obj-c.png"
                          width={120}
                          height={41}
                          alt="Objective-C iOS Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                  </tbody>
                </Table>
              </Col>

              <Col lg={3} md={6} xs={6} className="mb-3">
                <h4 className="tools-title"> Cross-Platform </h4>
                <Table className="mb-3" style={{ width: "fit-content" }}>
                  <tbody>
                    <tr>
                      <td className="new-bdr">
                        <Image
                          src="/images/react-native-mbl.png"
                          width={100}
                          height={34}
                          alt="React Native Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                      <td className="d-none d-lg-table-cell new-bdr">
                        <Image
                          src="/images/mbl-flutter.png"
                          width={110}
                          height={32}
                          alt="Flutter Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                    <tr>
                      <td className="d-lg-none new-bdr">
                        <Image
                          src="/images/mbl-flutter.png"
                          width={110}
                          height={32}
                          alt="Flutter Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                  </tbody>
                </Table>
              </Col>
              <Col lg={3} md={6} xs={6} className="mb-3">
                <h4 className="tools-title"> Android </h4>
                <Table className="mb-3" style={{ width: "fit-content" }}>
                  <tbody>
                    <tr>
                      <td className="new-bdr">
                        <Image
                          src="/images/Kotlin_logo.png"
                          width={110}
                          height={24}
                          alt="Kotlin Andriod Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                  </tbody>
                </Table>
              </Col>
              <Col lg={3} md={6} xs={6} className="mb-3">
                <h4 className="tools-title"> Hybrid </h4>
                <Table className="mb-3" style={{ width: "fit-content" }}>
                  <tbody>
                    <tr>
                      <td className="new-bdr">
                        <Image
                          src="/images/ionic.png"
                          width={110}
                          height={37}
                          alt="Ionic Application Development Logo"
                          className="mbl-tls"
                        />
                      </td>
                    </tr>
                  </tbody>
                </Table>
              </Col>
            </Row>
          </div>
        </section>

        <section id="recent-mbl-work">
          <div className="container new-ds">
            <div className="row">
              <div className="col-lg-3 col-md-3">
                <h2 className="case-heading">CASE STUDIES</h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="casecarousel-para">
                  In 6 years we have completed more than 200 individual projects
                  to develop modern websites, web and mobile applications for
                  clients from all over the world.
                </p>
              </div>
              <div className="col-lg-3 col-md-3">
                <button className="about-btn">
                  View All Cases{" "}
                  <img src="/images/material-symbols_arrow-right-alt.png" />
                </button>
              </div>
            </div>
            <CarouselComponent />
          </div>
        </section>

        <TestimonialClient />

        <section id="client" className="client-section">
          <div className="container mt-5">
            <Stack direction="horizontal">
              <div className=" badge-abot-btn">
                <img
                  src="/images/Rectangle-kariot.png"
                  className="me-2"
                  alt="design-dot"
                />
                <p> OUR CLIENTS </p>
              </div>
            </Stack>
            <div className="row pt-3">
              <div className="col-lg-6 col-md-6">
                <h2 className="client-title">We're A Trusted Growth Partner</h2>
              </div>
              <div className="col-lg-6 col-md-6">
                <p className="cliented-text">
                  At Minitzon, there is continuous learning that happens as we
                  work on various projects. We also love to update and upgrade
                  with the latest innovations in the field of technology and
                  apps.
                </p>
              </div>
            </div>
            <ClientLogo />
          </div>
        </section>
        <section id="contact" className="my-4 py-4">
          <div className="container contact-container">
            <div className="row py-2">
              <Stack direction="horizontal">
                <div className=" badge-abot-btn">
                  <img
                    src="/images/Rectangle-kariot.png"
                    className="me-2"
                    alt="design-dot"
                  />
                  <p> GET INTO TOUCH </p>
                </div>
              </Stack>
            </div>
            <div className="row">
              <div className="col-lg-8 col-md-8">
                <h2 className="contact-heading">
                  Hello! Let's make great work together.{" "}
                  <span> &#129304; </span>{" "}
                </h2>
                <p className="contact-text">
                  Take your startup to the next level. Our process revolves
                  around your unique business needs.
                </p>
              </div>
              <div className="col-lg-4 col-md-4">
                <Button href="/portfolio" className="cntct-btn">
                  <p>look at our</p> <h6>Case Studies</h6>{" "}
                </Button>
              </div>
            </div>
            <div className="row mt-5">
              <div className="col-lg-4 col-md-4">
                <h2 className="contct-heading">Hey! Got a startup idea?</h2>
                <p className="contct-para">
                  Let us give you our honest opinion. Book your{" "}
                  <strong style={{ color: "#1e2436" }}> FREE 30-Minute </strong>{" "}
                  consultation:
                </p>
                <div className="card contct-card">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/contact-us-mail.png"
                        width={50}
                        height={50}
                        alt="Contact us mail icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-10">
                      <p className="lets-para mb-0">Let's talk</p>
                      <Link href="/contact-us" className="lets-link">
                        Consult Our Experts
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Balaji Kailasasundaram
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card ceo-card">
                  <div className="row">
                    <div className="col-lg-3 col-md-12 col-3">
                      <Image
                        src="/images/person1.png"
                        width={74}
                        height={74}
                        alt="CEO Linked in profile image"
                        className="person-icon"
                      />
                    </div>
                    <div className="col-lg-9 col-md-12 col-9">
                      <h3 className="ceo-heading mb-0 pb-1">
                        Mr. Karthick Ganesan
                      </h3>
                      <p className="lets-para mb-0 pb-1">Co-Founder</p>
                      <h4 className="ceo-contact">
                        Phone No : <span>+91 72008 41581</span>
                      </h4>
                    </div>
                  </div>
                </div>
                <div className="card contct-card mt-4">
                  <div className="row">
                    <div className="col-lg-2 col-md-12 col-2">
                      <Image
                        src="/images/mailer-icon.png"
                        width={50}
                        height={50}
                        alt="Mailer icon"
                        className="contct-icon"
                      />
                    </div>
                    <div className="col-lg-10 col-md-12 col-9">
                      <p className="lets-para mb-0">Send us an email</p>
                      <Link
                        href="mailto:contact@trimsel.com"
                        className="lets-link"
                      >
                        contact@trimsel.com
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-8 col-md-8">
                <div className="card ntoct-card">
                  <h3 className="stages-heading">Have an idea?</h3>
                  <h3 className="cntoct-heading">Let's get in touch</h3>

                  <form id="home-form" onSubmit={handleSubmit(onSubmitForm)}>
                    <p className="mt-5 form-lbl-para"> I'm intrested in :</p>
                    <div className="options">
                      <input
                        {...register("product")}
                        type="radio"
                        name="selectOption"
                        value="Product Development"
                        id="product"
                        checked={selectedOption === "Product Development"}
                        onChange={handleOptionChange}
                        className="form-control"
                        placeholder="product"
                      />
                      <label
                        htmlFor="product"
                        className="abot-radio-style mt-3"
                      >
                        Product Development
                      </label>

                      <input
                        {...register("mobile-app")}
                        type="radio"
                        name="selectOption"
                        value="Mobile App Development"
                        id="mobile-app"
                        checked={selectedOption === "Mobile App Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="mobile-app"
                        className="abot-radio-style mt-3"
                      >
                        Mobile App Development
                      </label>

                      <input
                        {...register("cloud-devops")}
                        type="radio"
                        name="selectOption"
                        value="Cloud and DevOps"
                        id="cloud-devops"
                        checked={selectedOption === "Cloud and DevOps"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="cloud-devops"
                        className="abot-radio-style mt-3"
                      >
                        Cloud & DevOps
                      </label>
                      <input
                        {...register("website-development")}
                        type="radio"
                        name="selectOption"
                        value="Website Development"
                        id="website-development"
                        checked={selectedOption === "Website Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="website-development"
                        className="mt-3 abot-radio-style"
                      >
                        Website Development
                      </label>
                      <input
                        {...register("digital-marketing")}
                        type="radio"
                        name="selectOption"
                        value="Digital Marketing"
                        id="digital-marketing"
                        checked={selectedOption === "Digital Marketing"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="digital-marketing"
                        className="mt-3 abot-radio-style"
                      >
                        Digital Marketing
                      </label>
                      <input
                        {...register("blockchain-development")}
                        type="radio"
                        name="selectOption"
                        value="Blockchain Development"
                        id="blockchain-development"
                        checked={selectedOption === "Blockchain Development"}
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="blockchain-development"
                        className="mt-3 abot-radio-style"
                      >
                        Block Chain Development
                      </label>
                      <input
                        {...register("quality-testing")}
                        type="radio"
                        name="selectOption"
                        value="Quality Engineering and Technology"
                        id="quality-testing"
                        checked={
                          selectedOption ===
                          "Quality Engineering and Technology"
                        }
                        onChange={handleOptionChange}
                      />
                      <label
                        htmlFor="quality-testing"
                        className="mt-3 abot-radio-style"
                      >
                        Quality Engineering & Technology
                      </label>
                      <input
                        {...register("other")}
                        type="radio"
                        name="selectOption"
                        value="Other"
                        id="other"
                        checked={selectedOption === "Other"}
                        onChange={handleOptionChange}
                      />
                      <label htmlFor="other" className="mt-3 abot-radio-style">
                        Other
                      </label>
                    </div>
                    <div className="row py-3">
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("name", {
                              required: {
                                value: true,
                                message: "Your name is required",
                              },
                            })}
                            type="text"
                            id="name"
                            name="name"
                            className="form-control abot-form"
                            placeholder="Full Name*"
                          />
                          <span className="error-design pt-3">
                            {errors?.name?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("phone", {
                              required: {
                                value: true,
                                message: "Your phone number is required",
                              },
                              minLength: {
                                value: 10,
                                message: "Enter a valid mobile number",
                              },
                              maxLength: {
                                value: 11,
                                message: "Enter a valid mobile number",
                              },
                            })}
                            type="tel"
                            name="phone"
                            id="phone"
                            className="form-control abot-form"
                            placeholder="Mobile Number*"
                          />
                          <span className="error-design pt-3">
                            {errors?.phone?.message}
                            {errors?.phone?.maxLength?.message}
                            {errors?.phone?.minLength?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("email", {
                              required: {
                                value: true,
                                message: "Email id is required",
                              },
                              pattern: {
                                value:
                                  /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
                                message: "Enter a valid email address",
                              },
                            })}
                            type="email"
                            name="email"
                            id="email"
                            className="form-control abot-form"
                            placeholder="Email*"
                          />
                          <span className="error-design pt-3">
                            {errors?.email?.message}
                            {errors?.email?.pattern?.message}
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-6 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("skype")}
                            type="text"
                            name="skype"
                            id="skype"
                            className="form-control abot-form"
                            placeholder="SkypeID"
                          />
                        </div>
                      </div>
                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <input
                            {...register("company")}
                            type="text"
                            name="company"
                            id="company"
                            className="form-control abot-form"
                            placeholder="Company"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="md-form ps-3">
                          <textarea
                            {...register("message")}
                            type="textarea"
                            name="message"
                            id="message"
                            className="form-control  abot-form"
                            placeholder="Your Message"
                          />
                        </div>
                      </div>

                      <div className="col-lg-12 py-3">
                        <div className="text-right text-md-end">
                          <input type="submit" className="sbmt-btn" />
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="blog" className="py-4">
          <div className="container blog-container">
            <div className="row py-3">
              <Stack direction="horizontal">
                <div className=" badge-abot-btn">
                  <img
                    src="/images/Rectangle-kariot.png"
                    className="me-2"
                    alt="design-dot"
                  />
                  <p>
                    {" "}
                    <b> OUR BLOGS </b>{" "}
                  </p>
                </div>
              </Stack>
              <div className="col-lg-5 col-md-5 py-4">
                <h2 className="contacts-heading">
                  Read Our Latest Blogs and News
                </h2>
              </div>
              <div className="col-lg-7 col-md-7 py-4">
                <p className="blog-para">
                  At Minitzon, there is continuous learning that happens as we
                  work on various projects. We also love to update and upgrade
                  with the latest innovations in the field of technology and
                  apps.
                </p>
              </div>
            </div>
            <div className="row no-gutters">
              <div className="col-lg-6">
                <div className="card blog-card">
                  <div className="row no-gutters">
                    <div className="col-lg-5 col-md-5 py-3">
                      <img
                        className="card-img"
                        src="/images/blog-img.png"
                        alt=""
                      />
                    </div>
                    <div className="col-lg-7 col-md-7">
                      <Button className="card-badge mb-2">Development</Button>
                      <h5 className="blog-card-title">
                        Top 10 Mobile App Development Frameworks in 2023
                      </h5>
                      <p className="blog-card-para">
                        We've entered on age where our lives are...{" "}
                        <Link href="#">Read More</Link>
                      </p>
                    </div>
                  </div>
                  <div className="row no-gutters">
                    <div className="col-lg-5 col-md-5 py-3">
                      <img
                        className="card-img"
                        src="/images/blogs-img.png"
                        alt=""
                      />
                    </div>
                    <div className="col-lg-7 col-md-7 py-3">
                      <Button className="card-badge mb-2">Development</Button>
                      <h5 className="blog-card-title">
                        Top 10 Mobile App Development Frameworks in 2023
                      </h5>
                      <p className="blog-card-para">
                        We've entered on age where our lives are...{" "}
                        <Link href="#">Read More</Link>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-6">
                <div className="card blog-card">
                  <div className="card-image">
                    <img className="blog-image" src="/images/blog-image.png" />
                  </div>
                  <div className="card-content">
                    <Button className="card-badge my-2">Development</Button>
                    <h5 className="blogs-card-title">
                      How hybrid app development can help you build custom apps
                    </h5>
                    <p className="blog-card-para">
                      Digitization has taken over every industry and business
                      aspect. The pandemic only fuelled our shift tower...
                      <Link href="#">Read More</Link>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="faq">
          <div className="container faq-container">
            <h2 className="faq-heading">Frequently Asked Questions</h2>
            <Accordion defaultActiveKey="0" flush className="py-5">
              <Accordion.Item eventKey="0" className="pb-3">
                <Accordion.Header>
                  Why Choose Minitzon For Mobile App Development in India?
                </Accordion.Header>
                <Accordion.Body>
                  <p className="accordion-para">
                    Minitzon mobile app development company in Chennai has a
                    team of experienced developers with an in-depth knowledge of
                    frameworks and mobile technologies. They have the capacity
                    to meet demands on time without compromising on the quality
                    and functionalities. We are a recognised mobile app
                    development company in India for our robust apps and
                    cost-effective services.
                  </p>
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="1" className="pb-3">
                <Accordion.Header>
                  How Much Does It Cost To Build A Mobile App?
                </Accordion.Header>
                <Accordion.Body>
                  <p className="accordion-para">
                    Minitzon mobile app development company in Chennai has a
                    team of experienced developers with an in-depth knowledge of
                    frameworks and mobile technologies. They have the capacity
                    to meet demands on time without compromising on the quality
                    and functionalities. We are a recognised mobile app
                    development company in India for our robust apps and
                    cost-effective services.
                  </p>
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="2" className="pb-3">
                <Accordion.Header>
                  What Things To Consider When Hiring A Mobile App Development
                  Company?
                </Accordion.Header>
                <Accordion.Body>
                  <p className="accordion-para">
                    Minitzon mobile app development company in Chennai has a
                    team of experienced developers with an in-depth knowledge of
                    frameworks and mobile technologies. They have the capacity
                    to meet demands on time without compromising on the quality
                    and functionalities. We are a recognised mobile app
                    development company in India for our robust apps and
                    cost-effective services.
                  </p>
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="3" className="pb-3">
                <Accordion.Header>
                  Why Should I Choose A Mobile Application Development Company
                  In India?
                </Accordion.Header>
                <Accordion.Body>
                  <p className="accordion-para">
                    Minitzon mobile app development company in Chennai has a
                    team of experienced developers with an in-depth knowledge of
                    frameworks and mobile technologies. They have the capacity
                    to meet demands on time without compromising on the quality
                    and functionalities. We are a recognised mobile app
                    development company in India for our robust apps and
                    cost-effective services.
                  </p>
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="4" className="pb-3">
                <Accordion.Header>
                  How Long Does It Take To Build An App?
                </Accordion.Header>
                <Accordion.Body>
                  <p className="accordion-para">
                    Minitzon mobile app development company in Chennai has a
                    team of experienced developers with an in-depth knowledge of
                    frameworks and mobile technologies. They have the capacity
                    to meet demands on time without compromising on the quality
                    and functionalities. We are a recognised mobile app
                    development company in India for our robust apps and
                    cost-effective services.
                  </p>
                </Accordion.Body>
              </Accordion.Item>
            </Accordion>
          </div>
        </section>
        <ContactModal title="Wanna Develop A Mobile Application? Contact Us" />
        <Footer />
      </main>
    </>
  );
}
